# Užduotys
**Atkreipkite dėmesį, kad, jeigu neteisingai įvsite atsakymą, Out reikšmė irgi pasikeis**

In [81]:
import numpy as np
import random 

1\. Sukurkite vektorių su skaičiais nuo 1 iki 9

In [36]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2\. Sukurkite vektorių iš 10 nulių

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3\. Sukurkite vektorių iš 10 vienetų

In [34]:
# array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4\. Sukurkite vektorių iš 10 ketvertų

In [35]:
# array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])
np.linspace(4,4,10)

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

5\. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [41]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

6\. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam.

In [44]:
kintamasis = np.arange(1,25+1)
kintamasis

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [55]:
matrica = kintamasis.reshape(5,5)
matrica

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

7\. Iš matricos ištraukite skaičių 12

In [58]:
matrica[2,1]

12

8\. Iš matricos ištraukite paskutinę eilutę.

In [59]:
matrica[-1:]

array([[21, 22, 23, 24, 25]])

9\. Iš matricos ištraukite submatricą

1, 2, 3  
6, 7, 8  
11,12,13

In [62]:
matrica[:3,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

10\. Iš matricos ištraukite submatricą

7, 8, 9, 10  
12, 13, 14, 15  
17, 18, 19, 20

In [76]:
matrica[-4:4,-4:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

11\. Iš matricos ištraukite submatricą

16, 17, 18  
21, 22, 23

In [78]:
matrica[3:,:3]

array([[16, 17, 18],
       [21, 22, 23]])

12\. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam.

In [94]:
atsitiktine_seka = np.random.rand(20)

In [95]:
atsitiktine_seka

array([0.92108577, 0.58876852, 0.65162255, 0.65320693, 0.71362763,
       0.03703421, 0.20661711, 0.49679613, 0.06611911, 0.62783428,
       0.00292264, 0.08103516, 0.79646963, 0.13803073, 0.70673826,
       0.96873084, 0.95802892, 0.35352515, 0.24464087, 0.96037956])

13\. Suraskite didžiausią reikšmę masyve ir jos indeksą.

In [97]:
atsitiktine_seka.max()

0.968730840752424

In [98]:
atsitiktine_seka.argmax()

15

14\. Suraskite mažiausią reikšmę ir jos indeksą

In [99]:
atsitiktine_seka.min()

0.002922638733030669

In [100]:
atsitiktine_seka.argmin()

10

15\. Atspausdinkite šios matricos duomenų tipą

In [103]:
atsitiktine_seka.dtype

dtype('float64')

16\. Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90

In [121]:
integeriai = np.arange(1,100+1)

In [122]:
integeriai

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [125]:
integeriai[integeriai>90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

17\. Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius

In [134]:
 integeriai[integeriai % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

18\. Sukurkite tokią matricą:

In [55]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


In [283]:
kintamasis = np.arange(0,1)
np.linspace(0.025,1,40)

array([0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  , 0.225,
       0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  , 0.425, 0.45 ,
       0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  , 0.625, 0.65 , 0.675,
       0.7  , 0.725, 0.75 , 0.775, 0.8  , 0.825, 0.85 , 0.875, 0.9  ,
       0.925, 0.95 , 0.975, 1.   ])

19\. sukurkite tokią matricą (sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [74]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [297]:
np.linspace(1*4,1000,30)



array([   4.        ,   38.34482759,   72.68965517,  107.03448276,
        141.37931034,  175.72413793,  210.06896552,  244.4137931 ,
        278.75862069,  313.10344828,  347.44827586,  381.79310345,
        416.13793103,  450.48275862,  484.82758621,  519.17241379,
        553.51724138,  587.86206897,  622.20689655,  656.55172414,
        690.89655172,  725.24137931,  759.5862069 ,  793.93103448,
        828.27586207,  862.62068966,  896.96551724,  931.31034483,
        965.65517241, 1000.        ])

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

20\. **(BONUS)**
* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.
* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.
* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : **nauja_funkcija = np.vectorize(jūsų_funkcija)**  .
* Kadangi sąlygos reikšmių traukimui yra *bool* reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus
.

In [345]:
bonus = np.arange(1,100+1)
bonus


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [1]:
def ar_pirminis(sk):
    for el in range(2, sk):
        if sk % el == 0:
            return False

In [2]:
# nauja_funkcija = np.vectorize(ar_pirminis)
# bonus[nauja_funkcijas(bonus)]



array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])